baseURL = "http://flum.dev/"
languageCode = "en-us"
pluralizeListTitles = false

title = "Flum.dev"

theme= "flum-hugo"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
  email= "lifrank@grinnell.edu"
  icon= "fa fa-shower"
